site_name: Fiware-iotagent-json
site_url: https://fiware-iotagent-ul.readthedocs.org
repo_url: https://github.com/telefonicaid/iotagent-json.git
site_description: IoT Agent JSON (HTTP or MQTT) Documentation
docs_dir: docs
site_dir: html
markdown_extensions: [toc,fenced_code]
use_directory_urls: false
theme: readthedocs
extra_css: ["https://fiware.org/style/fiware_readthedocs.css"]

pages:
  - 'Home': 'index.md'
  - 'User & Programmers Manual':
    - 'Introduction': 'stepbystep.md'
    - 'API Walkthrough & Development intro': 'usermanual.md'
    - 'How to Contribute': 'contribution.md'
  - 'Installation & Administration Manual': 
    - 'Installation': 'installationguide.md'
    - 'Operations (logs & alarms)': 'operations.md'
